package maiden.processing

import shapeless._

object Countries {

  //CommonName, FormalName, CurrencyCode, TelephoneCode, TLD
  type Country = String :: String :: String :: Int :: String :: HNil

  val countries: Map[String,Country] = Map(
    "AF" -> ("Afghanistan" :: "Islamic State of Afghanistan" :: "AFN" :: 93 :: ".af" :: HNil),
    "AL" -> ("Albania" :: "Republic of Albania" :: "ALL" :: 355 :: ".al" :: HNil),
    "DZ" -> ("Algeria" :: "People's Democratic Republic of Algeria" :: "DZD" :: 213 :: ".dz" :: HNil),
    "AD" -> ("Andorra" :: "Principality of Andorra" :: "EUR" :: 376 :: ".ad" :: HNil),
    "AO" -> ("Angola" :: "Republic of Angola" :: "AOA" :: 244 :: ".ao" :: HNil),
    "AG" -> ("Antigua and Barbuda" :: "" :: "XCD" :: -267 :: ".ag" :: HNil),
    "AR" -> ("Argentina" :: "Argentine Republic" :: "ARS" :: 54 :: ".ar" :: HNil),
    "AM" -> ("Armenia" :: "Republic of Armenia" :: "AMD" :: 374 :: ".am" :: HNil),
    "AU" -> ("Australia" :: "Commonwealth of Australia" :: "AUD" :: 61 :: ".au" :: HNil),
    "AT" -> ("Austria" :: "Republic of Austria" :: "EUR" :: 43 :: ".at" :: HNil),
    "AZ" -> ("Azerbaijan" :: "Republic of Azerbaijan" :: "AZN" :: 994 :: ".az" :: HNil),
    "BS" -> ("Bahamas" :: "Commonwealth of The Bahamas" :: "BSD" :: 242 :: ".bs" :: HNil),
    "BH" -> ("Bahrain" :: "Kingdom of Bahrain" :: "BHD" :: 973 :: ".bh" :: HNil),
    "BD" -> ("Bangladesh" :: "People's Republic of Bangladesh" :: "BDT" :: 880 :: ".bd" :: HNil),
    "BB" -> ("Barbados" :: "" :: "BBD" :: -245 :: ".bb" :: HNil),
    "BY" -> ("Belarus" :: "Republic of Belarus" :: "BYR" :: 375 :: ".by" :: HNil),
    "BE" -> ("Belgium" :: "Kingdom of Belgium" :: "EUR" :: 32 :: ".be" :: HNil),
    "BZ" -> ("Belize" :: "" :: "BZD" :: 501 :: ".bz" :: HNil),
    "BJ" -> ("Benin" :: "Republic of Benin" :: "XOF" :: 229 :: ".bj" :: HNil),
    "BT" -> ("Bhutan" :: "Kingdom of Bhutan" :: "BTN" :: 975 :: ".bt" :: HNil),
    "BO" -> ("Bolivia" :: "Republic of Bolivia" :: "BOB" :: 591 :: ".bo" :: HNil),
    "BA" -> ("Bosnia and Herzegovina" :: "" :: "BAM" :: 387 :: ".ba" :: HNil),
    "BW" -> ("Botswana" :: "Republic of Botswana" :: "BWP" :: 267 :: ".bw" :: HNil),
    "BR" -> ("Brazil" :: "Federative Republic of Brazil" :: "BRL" :: 55 :: ".br" :: HNil),
    "BN" -> ("Brunei" :: "Negara Brunei Darussalam" :: "BND" :: 673 :: ".bn" :: HNil),
    "BG" -> ("Bulgaria" :: "Republic of Bulgaria" :: "BGN" :: 359 :: ".bg" :: HNil),
    "BF" -> ("Burkina Faso" :: "" :: "XOF" :: 226 :: ".bf" :: HNil),
    "BI" -> ("Burundi" :: "Republic of Burundi" :: "BIF" :: 257 :: ".bi" :: HNil),
    "KH" -> ("Cambodia" :: "Kingdom of Cambodia" :: "KHR" :: 855 :: ".kh" :: HNil),
    "CM" -> ("Cameroon" :: "Republic of Cameroon" :: "XAF" :: 237 :: ".cm" :: HNil),
    "CA" -> ("Canada" :: "" :: "CAD" :: 1 :: ".ca" :: HNil),
    "CV" -> ("Cape Verde" :: "Republic of Cape Verde" :: "CVE" :: 238 :: ".cv" :: HNil),
    "CF" -> ("Central African Republic" :: "" :: "XAF" :: 236 :: ".cf" :: HNil),
    "TD" -> ("Chad" :: "Republic of Chad" :: "XAF" :: 235 :: ".td" :: HNil),
    "CL" -> ("Chile" :: "Republic of Chile" :: "CLP" :: 56 :: ".cl" :: HNil),
    "CN" -> ("China" :: "People's Republic of China" :: "CNY" :: 86 :: ".cn" :: HNil),
    "CO" -> ("Colombia" :: "Republic of Colombia" :: "COP" :: 57 :: ".co" :: HNil),
    "KM" -> ("Comoros" :: "Union of Comoros" :: "KMF" :: 269 :: ".km" :: HNil),
    "CD" -> ("Congo (Kinshasa)" :: "Democratic Republic of the Congo" :: "CDF" :: 243 :: ".cd" :: HNil),
    "CG" -> ("Congo (Brazzaville)" :: "Republic of the Congo" :: "XAF" :: 242 :: ".cg" :: HNil),
    "CR" -> ("Costa Rica" :: "Republic of Costa Rica" :: "CRC" :: 506 :: ".cr" :: HNil),
    "CI" -> ("Cote d'Ivoire (Ivory Coast)" :: "Republic of Cote d'Ivoire" :: "XOF" :: 225 :: ".ci" :: HNil),
    "HR" -> ("Croatia" :: "Republic of Croatia" :: "HRK" :: 385 :: ".hr" :: HNil),
    "CU" -> ("Cuba" :: "Republic of Cuba" :: "CUP" :: 53 :: ".cu" :: HNil),
    "CY" -> ("Cyprus" :: "Republic of Cyprus" :: "CYP" :: 357 :: ".cy" :: HNil),
    "CZ" -> ("Czech Republic" :: "" :: "CZK" :: 420 :: ".cz" :: HNil),
    "DK" -> ("Denmark" :: "Kingdom of Denmark" :: "DKK" :: 45 :: ".dk" :: HNil),
    "DJ" -> ("Djibouti" :: "Republic of Djibouti" :: "DJF" :: 253 :: ".dj" :: HNil),
    "DM" -> ("Dominica" :: "Commonwealth of Dominica" :: "XCD" :: -766 :: ".dm" :: HNil),
    "DO" -> ("Dominican Republic" :: "" :: "DOP" :: 809 :: ".do" :: HNil),
    "EC" -> ("Ecuador" :: "Republic of Ecuador" :: "USD" :: 593 :: ".ec" :: HNil),
    "EG" -> ("Egypt" :: "Arab Republic of Egypt" :: "EGP" :: 20 :: ".eg" :: HNil),
    "SV" -> ("El Salvador" :: "Republic of El Salvador" :: "USD" :: 503 :: ".sv" :: HNil),
    "GQ" -> ("Equatorial Guinea" :: "Republic of Equatorial Guinea" :: "XAF" :: 240 :: ".gq" :: HNil),
    "ER" -> ("Eritrea" :: "State of Eritrea" :: "ERN" :: 291 :: ".er" :: HNil),
    "EE" -> ("Estonia" :: "Republic of Estonia" :: "EEK" :: 372 :: ".ee" :: HNil),
    "ET" -> ("Ethiopia" :: "Federal Democratic Republic of Ethiopia" :: "ETB" :: 251 :: ".et" :: HNil),
    "FJ" -> ("Fiji" :: "Republic of the Fiji Islands" :: "FJD" :: 679 :: ".fj" :: HNil),
    "FI" -> ("Finland" :: "Republic of Finland" :: "EUR" :: 358 :: ".fi" :: HNil),
    "FR" -> ("France" :: "French Republic" :: "EUR" :: 33 :: ".fr" :: HNil),
    "GA" -> ("Gabon" :: "Gabonese Republic" :: "XAF" :: 241 :: ".ga" :: HNil),
    "GM" -> ("Gambia" :: "Republic of The Gambia" :: "GMD" :: 220 :: ".gm" :: HNil),
    "GE" -> ("Georgia" :: "Republic of Georgia" :: "GEL" :: 995 :: ".ge" :: HNil),
    "DE" -> ("Germany" :: "Federal Republic of Germany" :: "EUR" :: 49 :: ".de" :: HNil),
    "GH" -> ("Ghana" :: "Republic of Ghana" :: "GHC" :: 233 :: ".gh" :: HNil),
    "GR" -> ("Greece" :: "Hellenic Republic" :: "EUR" :: 30 :: ".gr" :: HNil),
    "GD" -> ("Grenada" :: "" :: "XCD" :: -472 :: ".gd" :: HNil),
    "GT" -> ("Guatemala" :: "Republic of Guatemala" :: "GTQ" :: 502 :: ".gt" :: HNil),
    "GN" -> ("Guinea" :: "Republic of Guinea" :: "GNF" :: 224 :: ".gn" :: HNil),
    "GW" -> ("Guinea-Bissau" :: "Republic of Guinea-Bissau" :: "XOF" :: 245 :: ".gw" :: HNil),
    "GY" -> ("Guyana" :: "Co-operative Republic of Guyana" :: "GYD" :: 592 :: ".gy" :: HNil),
    "HT" -> ("Haiti" :: "Republic of Haiti" :: "HTG" :: 509 :: ".ht" :: HNil),
    "HN" -> ("Honduras" :: "Republic of Honduras" :: "HNL" :: 504 :: ".hn" :: HNil),
    "HU" -> ("Hungary" :: "Republic of Hungary" :: "HUF" :: 36 :: ".hu" :: HNil),
    "IS" -> ("Iceland" :: "Republic of Iceland" :: "ISK" :: 354 :: ".is" :: HNil),
    "IN" -> ("India" :: "Republic of India" :: "INR" :: 91 :: ".in" :: HNil),
    "ID" -> ("Indonesia" :: "Republic of Indonesia" :: "IDR" :: 62 :: ".id" :: HNil),
    "IR" -> ("Iran" :: "Islamic Republic of Iran" :: "IRR" :: 98 :: ".ir" :: HNil),
    "IQ" -> ("Iraq" :: "Republic of Iraq" :: "IQD" :: 964 :: ".iq" :: HNil),
    "IE" -> ("Ireland" :: "" :: "EUR" :: 353 :: ".ie" :: HNil),
    "IL" -> ("Israel" :: "State of Israel" :: "ILS" ::   972 :: ".il" :: HNil),
    "IT" -> ("Italy" :: "Italian Republic" :: "EUR" :: 39 :: ".it" :: HNil),
    "JM" -> ("Jamaica" :: "" :: "JMD" :: 876 :: ".jm" :: HNil),
    "JP" -> ("Japan" :: "" :: "JPY" :: 81 :: ".jp" :: HNil),
    "JO" -> ("Jordan" :: "Hashemite Kingdom of Jordan" :: "JOD" :: 962 :: ".jo" :: HNil),
    "KZ" -> ("Kazakhstan" :: "Republic of Kazakhstan" :: "KZT" :: 7 :: ".kz" :: HNil),
    "KE" -> ("Kenya" :: "Republic of Kenya" :: "KES" :: 254 :: ".ke" :: HNil),
    "KI" -> ("Kiribati" :: "Republic of Kiribati" :: "AUD" :: 686 :: ".ki" :: HNil),
    "KP" -> ("North Korea" :: "Democratic People's Republic of Korea" :: "KPW" :: 850 :: ".kp" :: HNil),
    "KR" -> ("South Korea" :: "Republic of Korea" :: "KRW" :: 82 :: ".kr" :: HNil),
    "KW" -> ("Kuwait" :: "State of Kuwait" :: "KWD" :: 965 :: ".kw" :: HNil),
    "KG" -> ("Kyrgyzstan" :: "Kyrgyz Republic" :: "KGS" :: 996 :: ".kg" :: HNil),
    "LA" -> ("Laos" :: "Lao People's Democratic Republic" :: "LAK" :: 856 :: ".la" :: HNil),
    "LV" -> ("Latvia" :: "Republic of Latvia" :: "LVL" :: 371 :: ".lv" :: HNil),
    "LB" -> ("Lebanon" :: "Lebanese Republic" :: "LBP" :: 961 :: ".lb" :: HNil),
    "LS" -> ("Lesotho" :: "Kingdom of Lesotho" :: "LSL" :: 266 :: ".ls" :: HNil),
    "LR" -> ("Liberia" :: "Republic of Liberia" :: "LRD" :: 231 :: ".lr" :: HNil),
    "LY" -> ("Libya" :: "Great Socialist People's Libyan Arab Jamahiriya" :: "LYD" :: 218 :: ".ly" :: HNil),
    "LI" -> ("Liechtenstein" :: "Principality of Liechtenstein" :: "CHF" :: 423 :: ".li" :: HNil),
    "LT" -> ("Lithuania" :: "Republic of Lithuania" :: "LTL" :: 370 :: ".lt" :: HNil),
    "LU" -> ("Luxembourg" :: "Grand Duchy of Luxembourg" :: "EUR" :: 352 :: ".lu" :: HNil),
    "MK" -> ("Macedonia" :: "Republic of Macedonia" :: "MKD" :: 389 :: ".mk" :: HNil),
    "MG" -> ("Madagascar" :: "Republic of Madagascar" :: "MGA" :: 261 :: ".mg" :: HNil),
    "MW" -> ("Malawi" :: "Republic of Malawi" :: "MWK" :: 265 :: ".mw" :: HNil),
    "MY" -> ("Malaysia" :: "" :: "MYR" :: 60 :: ".my" :: HNil),
    "MV" -> ("Maldives" :: "Republic of Maldives" :: "MVR" :: 960 :: ".mv" :: HNil),
    "ML" -> ("Mali" :: "Republic of Mali" :: "XOF" :: 223 :: ".ml" :: HNil),
    "MT" -> ("Malta" :: "Republic of Malta" :: "MTL" :: 356 :: ".mt" :: HNil),
    "MH" -> ("Marshall Islands" :: "Republic of the Marshall Islands" :: "USD" :: 692 :: ".mh" :: HNil),
    "MR" -> ("Mauritania" :: "Islamic Republic of Mauritania" :: "MRO" :: 222 :: ".mr" :: HNil),
    "MU" -> ("Mauritius" :: "Republic of Mauritius" :: "MUR" :: 230 :: ".mu" :: HNil),
    "MX" -> ("Mexico" :: "United Mexican States" :: "MXN" :: 52 :: ".mx" :: HNil),
    "FM" -> ("Micronesia" :: "Federated States of Micronesia" :: "USD" :: 691 :: ".fm" :: HNil),
    "MD" -> ("Moldova" :: "Republic of Moldova" :: "MDL" :: 373 :: ".md" :: HNil),
    "MC" -> ("Monaco" :: "Principality of Monaco" :: "EUR" :: 377 :: ".mc" :: HNil),
    "MN" -> ("Mongolia" :: "" :: "MNT" :: 976 :: ".mn" :: HNil),
    "ME" -> ("Montenegro" :: "Republic of Montenegro" :: "EUR" :: 382 :: ".me and .yu" :: HNil),
    "MA" -> ("Morocco" :: "Kingdom of Morocco" :: "MAD" :: 212 :: ".ma" :: HNil),
    "MZ" -> ("Mozambique" :: "Republic of Mozambique" :: "MZM" :: 258 :: ".mz" :: HNil),
    "MM" -> ("Myanmar (Burma)" :: "Union of Myanmar" :: "MMK" :: 95 :: ".mm" :: HNil),
    "NA" -> ("Namibia" :: "Republic of Namibia" :: "NAD" :: 264 :: ".na" :: HNil),
    "NR" -> ("Nauru" :: "Republic of Nauru" :: "AUD" :: 674 :: ".nr" :: HNil),
    "NP" -> ("Nepal" :: "" :: "NPR" :: 977 :: ".np" :: HNil),
    "NL" -> ("Netherlands" :: "Kingdom of the Netherlands" :: "EUR" :: 31 :: ".nl" :: HNil),
    "NZ" -> ("New Zealand" :: "" :: "NZD" :: 64 :: ".nz" :: HNil),
    "NI" -> ("Nicaragua" :: "Republic of Nicaragua" :: "NIO" :: 505 :: ".ni" :: HNil),
    "NE" -> ("Niger" :: "Republic of Niger" :: "XOF" :: 227 :: ".ne" :: HNil),
    "NG" -> ("Nigeria" :: "Federal Republic of Nigeria" :: "NGN" :: 234 :: ".ng" :: HNil),
    "NO" -> ("Norway" :: "Kingdom of Norway" :: "NOK" :: 47 :: ".no" :: HNil),
    "OM" -> ("Oman" :: "Sultanate of Oman" :: "OMR" :: 968 :: ".om" :: HNil),
    "PK" -> ("Pakistan" :: "Islamic Republic of Pakistan" :: "PKR" :: 92 :: ".pk" :: HNil),
    "PW" -> ("Palau" :: "Republic of Palau" :: "USD" :: 680 :: ".pw" :: HNil),
    "PA" -> ("Panama" :: "Republic of Panama" :: "PAB" :: 507 :: ".pa" :: HNil),
    "PG" -> ("Papua New Guinea" :: "Independent State of Papua New Guinea" :: "PGK" :: 675 :: ".pg" :: HNil),
    "PY" -> ("Paraguay" :: "Republic of Paraguay" :: "PYG" :: 595 :: ".py" :: HNil),
    "PE" -> ("Peru" :: "Republic of Peru" :: "PEN" :: 51 :: ".pe" :: HNil),
    "PH" -> ("Philippines" :: "Republic of the Philippines" :: "PHP" :: 63 :: ".ph" :: HNil),
    "PL" -> ("Poland" :: "Republic of Poland" :: "PLN" :: 48 :: ".pl" :: HNil),
    "PT" -> ("Portugal" :: "Portuguese Republic" :: "EUR" :: 351 :: ".pt" :: HNil),
    "QA" -> ("Qatar" :: "State of Qatar" :: "QAR" :: 974 :: ".qa" :: HNil),
    "RO" -> ("Romania" :: "" :: "RON" :: 40 :: ".ro" :: HNil),
    "RU" -> ("Russia" :: "Russian Federation" :: "RUB" :: 7 :: ".ru" :: HNil),
    "RW" -> ("Rwanda" :: "Republic of Rwanda" :: "RWF" :: 250 :: ".rw" :: HNil),
    "KN" -> ("Saint Kitts and Nevis" :: "Federation of Saint Kitts and Nevis" :: "XCD" :: -868 :: ".kn" :: HNil),
    "LC" -> ("Saint Lucia" :: "" :: "XCD" :: -757 :: ".lc" :: HNil),
    "WS" -> ("Samoa" :: "Independent State of Samoa" :: "WST" :: 685 :: ".ws" :: HNil),
    "SM" -> ("San Marino" :: "Republic of San Marino" :: "EUR" :: 378 :: ".sm" :: HNil),
    "ST" -> ("Sao Tome and Principe" :: "Democratic Republic of Sao Tome and Principe" :: "STD" :: 239 :: ".st" :: HNil),
    "SA" -> ("Saudi Arabia" :: "Kingdom of Saudi Arabia" :: "SAR" :: 966 :: ".sa" :: HNil),
    "SN" -> ("Senegal" :: "Republic of Senegal" :: "XOF" :: 221 :: ".sn" :: HNil),
    "RS" -> ("Serbia" :: "Republic of Serbia" :: "RSD" :: 381 :: ".rs and .yu" :: HNil),
    "SC" -> ("Seychelles" :: "Republic of Seychelles" :: "SCR" :: 248 :: ".sc" :: HNil),
    "SL" -> ("Sierra Leone" :: "Republic of Sierra Leone" :: "SLL" :: 232 :: ".sl" :: HNil),
    "SG" -> ("Singapore" :: "Republic of Singapore" :: "SGD" :: 65 :: ".sg" :: HNil),
    "SK" -> ("Slovakia" :: "Slovak Republic" :: "SKK" :: 421 :: ".sk" :: HNil),
    "SI" -> ("Slovenia" :: "Republic of Slovenia" :: "EUR" :: 386 :: ".si" :: HNil),
    "SB" -> ("Solomon Islands" :: "" :: "SBD" :: 677 :: ".sb" :: HNil),
    "SO" -> ("Somalia" :: "" :: "SOS" :: 252 :: ".so" :: HNil),
    "ZA" -> ("South Africa" :: "Republic of South Africa" :: "ZAR" :: 27 :: ".za" :: HNil),
    "ES" -> ("Spain" :: "Kingdom of Spain" :: "EUR" :: 34 :: ".es" :: HNil),
    "LK" -> ("Sri Lanka" :: "Democratic Socialist Republic of Sri Lanka" :: "LKR" :: 94 :: ".lk" :: HNil),
    "SD" -> ("Sudan" :: "Republic of the Sudan" :: "SDD" :: 249 :: ".sd" :: HNil),
    "SR" -> ("Suriname" :: "Republic of Suriname" :: "SRD" :: 597 :: ".sr" :: HNil),
    "SZ" -> ("Swaziland" :: "Kingdom of Swaziland" :: "SZL" :: 268 :: ".sz" :: HNil),
    "SE" -> ("Sweden" :: "Kingdom of Sweden" :: "SEK" :: 46 :: ".se" :: HNil),
    "CH" -> ("Switzerland" :: "Swiss Confederation" :: "CHF" :: 41 :: ".ch" :: HNil),
    "SY" -> ("Syria" :: "Syrian Arab Republic" :: "SYP" :: 963 :: ".sy" :: HNil),
    "TJ" -> ("Tajikistan" :: "Republic of Tajikistan" :: "TJS" :: 992 :: ".tj" :: HNil),
    "TZ" -> ("Tanzania" :: "United Republic of Tanzania" :: "TZS" :: 255 :: ".tz" :: HNil),
    "TH" -> ("Thailand" :: "Kingdom of Thailand" :: "THB" :: 66 :: ".th" :: HNil),
    "TL" -> ("Timor-Leste (East Timor)" :: "Democratic Republic of Timor-Leste" :: "USD" :: 670 :: ".tp" :: HNil),
    "TG" -> ("Togo" :: "Togolese Republic" :: "XOF" :: 228 :: ".tg" :: HNil),
    "TO" -> ("Tonga" :: "Kingdom of Tonga" :: "TOP" :: 676 :: ".to" :: HNil),
    "TT" -> ("Trinidad and Tobago" :: "Republic of Trinidad and Tobago" :: "TTD" :: 1868 :: ".tt" :: HNil),
    "TN" -> ("Tunisia" :: "Tunisian Republic" :: "TND" :: 216 :: ".tn" :: HNil),
    "TR" -> ("Turkey" :: "Republic of Turkey" :: "TRY" :: 90 :: ".tr" :: HNil),
    "TM" -> ("Turkmenistan" :: "" :: "TMM" :: 993 :: ".tm" :: HNil),
    "TV" -> ("Tuvalu" :: "" :: "AUD" :: 688 :: ".tv" :: HNil),
    "UG" -> ("Uganda" :: "Republic of Uganda" :: "UGX" :: 256 :: ".ug" :: HNil),
    "UA" -> ("Ukraine" :: "" :: "UAH" :: 380 :: ".ua" :: HNil),
    "AE" -> ("United Arab Emirates" :: "United Arab Emirates" :: "AED" :: 971 :: ".ae" :: HNil),
    "GB" -> ("United Kingdom" :: "United Kingdom of Great Britain and Northern Ireland" :: "GBP" :: 44 :: ".uk" :: HNil),
    "US" -> ("United States" :: "United States of America" :: "USD" :: 1 :: ".us" :: HNil),
    "UY" -> ("Uruguay" :: "Oriental Republic of Uruguay" :: "UYU" :: 598 :: ".uy" :: HNil),
    "UZ" -> ("Uzbekistan" :: "Republic of Uzbekistan" :: "UZS" :: 998 :: ".uz" :: HNil),
    "VU" -> ("Vanuatu" :: "Republic of Vanuatu" :: "VUV" :: 678 :: ".vu" :: HNil),
    "VA" -> ("Vatican City" :: "State of the Vatican City" :: "EUR" :: 379 :: ".va" :: HNil),
    "VE" -> ("Venezuela" :: "Bolivarian Republic of Venezuela" :: "VEB" :: 58 :: ".ve" :: HNil),
    "VN" -> ("Vietnam" :: "Socialist Republic of Vietnam" :: "VND" :: 84 :: ".vn" :: HNil),
    "YE" -> ("Yemen" :: "Republic of Yemen" :: "YER" :: 967 :: ".ye" :: HNil),
    "ZM" -> ("Zambia" :: "Republic of Zambia" :: "ZMK" :: 260 :: ".zm" :: HNil),
    "ZW" -> ("Zimbabwe" :: "Republic of Zimbabwe" :: "ZWD" :: 263 :: ".zw" :: HNil),
    "GE" -> ("Abkhazia" :: "Republic of Abkhazia" :: "RUB" :: 995 :: ".ge" :: HNil),
    "TW" -> ("Taiwan" :: "Republic of China" :: "TWD" :: 886 :: ".tw" :: HNil),
    "AZ" -> ("Nagorno-Karabakh" :: "Nagorno-Karabakh Republic" :: "AMD" :: 277 :: ".az" :: HNil),
    "SO" -> ("Somaliland" :: "Republic of Somaliland" :: "" :: 252 :: ".so" :: HNil),
    "GE" -> ("South Ossetia" :: "Republic of South Ossetia" :: "RUB and GEL" :: 995 :: ".ge" :: HNil),
    "CX" -> ("Christmas Island" :: "Territory of Christmas Island" :: "AUD" :: 61 :: ".cx" :: HNil),
    "CC" -> ("Cocos (Keeling) Islands" :: "Territory of Cocos (Keeling) Islands" :: "AUD" :: 61 :: ".cc" :: HNil),
    "NF" -> ("Norfolk Island" :: "Territory of Norfolk Island" :: "AUD" :: 672 :: ".nf" :: HNil),
    "NC" -> ("New Caledonia" :: "" :: "XPF" :: 687 :: ".nc" :: HNil),
    "PF" -> ("French Polynesia" :: "Overseas Country of French Polynesia" :: "XPF" :: 689 :: ".pf" :: HNil),
    "YT" -> ("Mayotte" :: "Departmental Collectivity of Mayotte" :: "EUR" :: 262 :: ".yt" :: HNil),
    "GP" -> ("Saint Barthelemy" :: "Collectivity of Saint Barthelemy" :: "EUR" :: 590 :: ".gp" :: HNil),
    "GP" -> ("Saint Martin" :: "Collectivity of Saint Martin" :: "EUR" :: 590 :: ".gp" :: HNil),
    "PM" -> ("Saint Pierre and Miquelon" :: "Territorial Collectivity of Saint Pierre and Miquelon" :: "EUR" :: 508 :: ".pm" :: HNil),
    "WF" -> ("Wallis and Futuna" :: "Collectivity of the Wallis and Futuna Islands" :: "XPF" :: 681 :: ".wf" :: HNil),
    "CK" -> ("Cook Islands" :: "" :: "NZD" :: 682 :: ".ck" :: HNil),
    "NU" -> ("Niue" :: "" :: "NZD" :: 683 :: ".nu" :: HNil),
    "TK" -> ("Tokelau" :: "" :: "NZD" :: 690 :: ".tk" :: HNil),
    "GG" -> ("Guernsey" :: "Bailiwick of Guernsey" :: "GGP" :: 44 :: ".gg" :: HNil),
    "IM" -> ("Isle of Man" :: "" :: "IMP" :: 44 :: ".im" :: HNil),
    "JE" -> ("Jersey" :: "Bailiwick of Jersey" :: "JEP" :: 44 :: ".je" :: HNil),
    "AI" -> ("Anguilla" :: "" :: "XCD" :: -263 :: ".ai" :: HNil),
    "BM" -> ("Bermuda" :: "" :: "BMD" :: 809 :: ".bm" :: HNil),
    "VG" -> ("British Virgin Islands" :: "" :: "USD" :: 284 :: ".vg" :: HNil),
    "KY" -> ("Cayman Islands" :: "" :: "KYD" :: -344 :: ".ky" :: HNil),
    "FK" -> ("Falkland Islands (Islas Malvinas)" :: "" :: "FKP" :: 500 :: ".fk" :: HNil),
    "GI" -> ("Gibraltar" :: "" :: "GIP" :: 350 :: ".gi" :: HNil),
    "MS" -> ("Montserrat" :: "" :: "XCD" :: -663 :: ".ms" :: HNil),
    "SH" -> ("Saint Helena" :: "" :: "SHP" :: 290 :: ".sh" :: HNil),
    "PR" -> ("Puerto Rico" :: "Commonwealth of Puerto Rico" :: "USD" :: 787 :: ".pr" :: HNil),
    "AS" -> ("American Samoa" :: "Territory of American Samoa" :: "USD" :: 684 :: ".as" :: HNil),
    "GU" -> ("Guam" :: "Territory of Guam" :: "USD" :: 671 :: ".gu" :: HNil),
    "VI" -> ("U.S. Virgin Islands" :: "United States Virgin Islands" :: "USD" :: 340 :: ".vi" :: HNil),
    "HK" -> ("Hong Kong" :: "Hong Kong Special Administrative Region" :: "HKD" :: 852 :: ".hk" :: HNil),
    "MO" -> ("Macau" :: "Macau Special Administrative Region" :: "MOP" :: 853 :: ".mo" :: HNil),
    "FO" -> ("Faroe Islands" :: "" :: "DKK" :: 298 :: ".fo" :: HNil),
    "GL" -> ("Greenland" :: "" :: "DKK" :: 299 :: ".gl" :: HNil),
    "GF" -> ("French Guiana" :: "Overseas Region of Guiana" :: "EUR" :: 594 :: ".gf" :: HNil),
    "GP" -> ("Guadeloupe" :: "Overseas Region of Guadeloupe" :: "EUR" :: 590 :: ".gp" :: HNil),
    "MQ" -> ("Martinique" :: "Overseas Region of Martinique" :: "EUR" :: 596 :: ".mq" :: HNil),
    "RE" -> ("Reunion" :: "Overseas Region of Reunion" :: "EUR" :: 262 :: ".re" :: HNil),
    "AX" -> ("Aland" :: "" :: "EUR" :: 340 :: ".ax" :: HNil),
    "AW" -> ("Aruba" :: "" :: "AWG" :: 297 :: ".aw" :: HNil),
    "AN" -> ("Netherlands Antilles" :: "" :: "ANG" :: 599 :: ".an" :: HNil),
    "SJ" -> ("Svalbard" :: "" :: "NOK" :: 47 :: ".sj" :: HNil),
    "AC" -> ("Ascension" :: "" :: "SHP" :: 247 :: ".ac" :: HNil),
    "TA" -> ("Tristan da Cunha" :: "" :: "SHP" :: 290 :: "" :: HNil)
  )



}
